Q1. Pandas version

In [2]:
import pandas as pd

In [4]:
pd.__version__

'2.1.4'

Q2. Records count

In [8]:
df_laptops = pd.read_csv('laptops.csv')

In [19]:
len(df_laptops)

2160

Q3. Laptop brands

In [17]:
brands = df_laptops.groupby('Brand')

In [18]:
len(brands)

27

Q4. Missing values

In [20]:
import numpy as np

In [21]:
missing_values_count = df_laptops.isnull().sum()

In [22]:
columns_with_missing_values = missing_values_count[missing_values_count > 0]

In [23]:
len(columns_with_missing_values)

3

Q5. Maximum final price. What's the maximum final price of Dell notebooks in the dataset?

In [26]:
dell_laptops = df_laptops[df_laptops['Brand'] == 'Dell']

In [30]:
dell_laptops['Final Price'].max()

3936.0

Q6. Median value of Screen.

In [31]:
# Find the median value of Screen column in the dataset.
df_laptops['Screen'].median()

15.6

In [33]:
# Next, calculate the most frequent value of the same Screen column.
df_laptops['Screen'].mode()[0]

15.6

In [35]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
fill_missing_values = df_laptops['Screen'].fillna(df_laptops['Screen'].mode()[0], inplace=True)

In [36]:
# Now, calculate the median value of Screen once again.
df_laptops['Screen'].median()

15.6

Q7. Sum of weights

In [38]:
# Select all the "Innjoo" laptops from the dataset.
Innjoo_brand = df_laptops[df_laptops['Brand'] == 'Innjoo']

In [39]:
len(Innjoo_brand)

6

In [44]:
# Select only columns RAM, Storage, Screen.
innjoo_brand = Innjoo_brand[['RAM', 'Storage', 'Screen']]

In [45]:
# Get the underlying NumPy array. Let's call it X.
X = innjoo_brand.values

In [46]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [47]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)

In [48]:
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [49]:
# Compute the inverse of XTX.
inverse_XTX = np.linalg.inv(XTX)

In [50]:
print(inverse_XTX)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [51]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [53]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = inverse_XTX.dot(X.T).dot(y)

In [54]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [59]:
# What's the sum of all the elements of the result?
w.sum().round(2)

91.3